name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/hello-world-app:latest .
        docker push your-dockerhub-username/hello-world-app:latest

    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize and Apply Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var='subnet_ids=${{ secrets.SUBNET_IDS }}' -var='security_group_ids=${{ secrets.SECURITY_GROUP_IDS }}'
